### ISSUE TITLE
Send message from another deivce

### ISSUE THREAD

**Issue by goyzhang** [ChanyaVRC/VRCOscLib#8]
The `OscUtility.OscClient` is set to be loopback, this assumes the controller and VRC are running on the same device.
However, if I want to control it from a remote device in LAN:

` MyAndroid(192.168.1.200) -> VRC(192.168.1.201)`

I should be able to change the target IP.

---
In a more complicated case, I want to control two VRC instances from one PC.
```
 MyPC(192.168.1.200) -> VRC(192.168.1.201)
                     -> VRC(192.168.1.202)
```
Well this could be hard as the library is pretty much static (turn to OscCore instead?).

**Comment by ChanyaVRC** [comment]
> I should be able to change the target IP.

I think too, and this will be implemented soon.
Why aren't you implementing this, @ChanyaVRC?

> Well this could be hard as the library is pretty much static (turn to OscCore instead?).

That's true. It is very difficult to prepare an instance while guaranteeing unique light syntax of this library.
In the first place, it is not supposed to run multiple VRChat instances (while synchronizing with one application). Such situations do not normally exist, and the complexity of the setting makes it difficult to create end-user-friendly applications with this feature. This means that this feature is for personal developer applications.
I don't think there is demand.

If you **really** want to run multiple clients in a single application, use `BuildSoft.OscCore.OscClient`.
